global:
  name: Urban Computing Interactive Landscape
  short_name: UCF
  repo: ucfoundation/ucf-landscape
  website: https://landscape.uc.foundation
  short_domain: l.uc.foundation
  company_url: https://uc.foundation
  email: info@ucf.foundation
  membership: UCF Members
  self: https://www.crunchbase.com/organization/urban-computing-foundation
  slack_channel: T08PSQ7BQ/BP35P3221/v1CnqrqSRZkUpKc5pf2I80rQ
  meta:
    title: UCF Landscape
    fb_admin: alex.contini.94
    description: Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets
    twitter: '@ucfdn'
    google_site_verification: ZqfZR8nee99-8ahhH84ebVHeQaqqHzqhy1RND0De7XU
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
    membership: UCF Members
  flags:
    companies: UCF Members
twitter:
  search: landscape.ucf.foundation
  url: https://landscape.uc.foundation
  text: Urban Computing Landscape from @ucfdn
relation:
  label: UCF Relation
  url: ucf
  values:
    - id: hosted
      label: UCF Projects
      children:
        - id: graduated
          label: Graduated UCF Projects
          prefix: UCF
          tag: Graduated
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: UCF Graduated
          big_picture_color: rgb(24,54,114)
        - id: incubating
          label: Incubating UCF Projects
          prefix: UCF
          tag: Incubating
          color: '#00cbff'
          big_picture_order: 2
          big_picture_label: UCF Incubating
          big_picture_color: rgb(83, 113, 189)
    - id: company
      label: UCF Members
      tag: Company
      big_picture_order: 3
    - id: member
      label: UCF Member Products/Projects
      tag: UCF Member
    - id: false
      label: Non-ucf Member Products/Projects
      url: 'no'
membership:
  Premier:
    name: UCF
    label: Premier Member
    funding: Premier
    is_large: true
  General:
    name: UCF
    label: Member
    funding: General
    is_large: true
  Associate:
    name: UCF
    label: Member
    funding: Associate
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: https://www.crunchbase.com/organization/linux-foundation
  'false':
    funding: 'No'
home:
  header: >
    <h1>Urban Computing Foundation Interactive Landscape</h1> The UCF landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based
    on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/?utm_source=lfdl_landscape&utm_medium=web&utm_campaign=kccnceu20
    image: /images/info1.jpg
    title: Kubecon + CloudNativeCon Europe 2020
presets:
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /license=apache-license-2-0
    label: Apache-2.0 landscape
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
  - url: /format=card-mode&grouping=no&sort=amount
    label: Cards by MCap/Funding
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: Urban Computing Foundation Landscape
    fullscreen_header: See the interactive landscape at l.uc.foundation
    elements:
      - type: HorizontalCategory
        category: Mapping
        rows: 3
        width: 380
        height: 160
        top: 0
        left: 0
        color: rgb(37,81,209)
        fit_width: true
      - type: HorizontalCategory
        category: Data Visualization
        rows: 3
        width: 425
        height: 160
        top: 0
        left: 400
        color: rgb(29,119,164)
        fit_width: true
      - type: HorizontalCategory
        category: Location Data
        rows: 3
        width: 270
        height: 160
        top: 0
        left: 845
        color: rgb(19,105,73)
        fit_width: true
      - type: HorizontalCategory
        category: Data Acquisition, Sensors, and IoT
        rows: 3
        width: 300
        height: 160
        top: 190
        left: 0
        color: rgb(126,115,14)
        fit_width: true
      - type: HorizontalCategory
        category: GIS and Data Analysis
        rows: 3
        width: 300
        height: 160
        top: 190
        left: 320
        color: rgb(87,43,10)
        fit_width: true
      - type: HorizontalCategory
        category: Data Exchange File Formats and Specs
        rows: 4
        width: 475
        height: 160
        top: 190
        left: 640
        color: rgb(79,121,13)
        fit_width: true
      - type: HorizontalCategory
        category: GIS Infrastructure
        rows: 4
        width: 300
        height: 160
        top: 380
        left: 0
        color: rgb(193,83,21)
        fit_width: true
      - type: HorizontalCategory
        category: Geospatial Data Transformation
        rows: 4
        width: 475
        height: 160
        top: 380
        left: 320
        color: rgb(185,33,66)
        fit_width: true
      - type: HorizontalCategory
        category: Geospatial Data Portals
        rows: 4
        width: 300
        height: 160
        top: 380
        left: 815
        color: rgb(111,12,52)
        fit_width: true
      - type: HorizontalCategory
        category: UCF Members
        rows: 3
        width: 675
        height: 160
        top: 570
        left: 0
        color: rgb(179,60,133)
        fit_width: true
      - type: LandscapeInfo
        width: 420
        height: 160
        top: 570
        left: 695
        children:
          - type: text
            text: |
              This landscape is intended as a map to explore open source urban computing projects, and lists the members of the Urban Computing Foundation.
            top: 15
            left: 100
            right: 120
            font_size: 10
          - type: image
            image: qr.svg
            top: 10
            left: 5
            width: 90
            height: 90
            title: QR Code
          - type: title
            title: l.ucf.foundation
            top: 99
            left: 9
            font_size: 12
          - type: image
            image: left-logo.svg
            width: 110
            right: 5
            top: 15
            title: Landscape Logo
          - type: image
            image: right-logo.svg
            width: 109
            right: 5
            top: 55
            title: UC Foundation Logo
test:
  header: Urban Computing Foundation Interactive Landscape
  section: UCF Members
  logo: tensorflow.svg
update_server:
  ip: 147.75.106.211
  update_hour: 0
  update_minute: 0
